version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      ERGAST_API_BASE: https://api.jolpi.ca/ergast/
      REDIS_HOST: redis
    ports:
      - "4000:4000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://localhost:4000/api/
    ports:
      - "5173:5173"
    depends_on:
      - backend
