version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      ERGAST_API_BASE: https://ergast.com/api/
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend
