[project]
name = "my-fullstack-app"

[services.client]
source = "client"
dockerfilePath = "client/Dockerfile"

  [services.client.start]
  cmd = ""
  port = 80

[services.server]
source = "server"
dockerfilePath = "server/Dockerfile"

  [services.server.start]
  cmd = ""
  port = 4000
