[build]
root = "."
dockerfile = "Dockerfile"

[deploy]
startCommand = "node dist/index.js"

[env]
ERGAST_API_BASE = "https://api.jolpi.ca/ergast/"
REDIS_HOST = "redis"
DATABASE_URL = "postgres://neondb_owner:npg_yT2IqecvrF9z@postgres:5432/neondb"
