name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-backend:
    name: Install Backend Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: cd server && npm ci

  install-client:
    name: Install Client Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: cd client && npm ci

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    needs: install-backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: cd server && npm ci
      - run: cd server && npm run lint

  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    needs: install-client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: cd client && npm ci
      - run: cd client && npm run lint

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: install-backend
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:secret@localhost:5432/postgres
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: cd server && npm ci
      - run: cd server && npm test

  test-client:
    name: Test Client
    runs-on: ubuntu-latest
    needs: install-client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: cd client && npm ci
      - run: cd client && npm test
