name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  BACKEND_IMAGE_NAME: f1-backend
  FRONTEND_IMAGE_NAME: f1-frontend

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE_NAME:latest -f server/Dockerfile ./server

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE_NAME:latest

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE_NAME:latest -f client/Dockerfile ./client

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE_NAME:latest
