name: Snyk Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snyk
        run: npm install -g snyk

      # Server
      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run Snyk on server
        run: snyk test --severity-threshold=high
        working-directory: ./server
        env:
          SNYK_TOKEN: b9898c46-f1dd-407b-be7c-2661c0f387e1

      # Client
      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Run Snyk on client
        run: snyk test --severity-threshold=high
        working-directory: ./client
        env:
          SNYK_TOKEN: b9898c46-f1dd-407b-be7c-2661c0f387e1
