name: Trivy Docker Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Trivy Scan Backend & Frontend Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend-image ./server

      - name: Build frontend image
        run: docker build -t frontend-image ./client

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan backend image with Trivy
        run: trivy image --severity HIGH,CRITICAL backend-image

      - name: Scan frontend image with Trivy
        run: trivy image --severity HIGH,CRITICAL frontend-image
